// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	decimal "pkg/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockCurrencyService is an autogenerated mock type for the CurrencyService type
type MockCurrencyService struct {
	mock.Mock
}

// GetRates provides a mock function with given fields: ctx
func (_m *MockCurrencyService) GetRates(ctx context.Context) (map[string]decimal.Decimal, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRates")
	}

	var r0 map[string]decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]decimal.Decimal, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]decimal.Decimal); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]decimal.Decimal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCurrencyService creates a new instance of MockCurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurrencyService {
	mock := &MockCurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
