// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	model "exchange/internal/services/dsp/model"

	mock "github.com/stretchr/testify/mock"
)

// MockDSPService is an autogenerated mock type for the DSPService type
type MockDSPService struct {
	mock.Mock
}

// GetDSPs provides a mock function with given fields: _a0, _a1
func (_m *MockDSPService) GetDSPs(_a0 context.Context, _a1 model.GetDSPsReq) ([]model.DSP, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetDSPs")
	}

	var r0 []model.DSP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetDSPsReq) ([]model.DSP, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetDSPsReq) []model.DSP); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DSP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetDSPsReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDSPService creates a new instance of MockDSPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDSPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDSPService {
	mock := &MockDSPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
