// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	model "exchange/internal/services/analyticWriter/model"

	mock "github.com/stretchr/testify/mock"
)

// MockAnalyticWriterService is an autogenerated mock type for the AnalyticWriterService type
type MockAnalyticWriterService struct {
	mock.Mock
}

// CreateDSPToExchangeResponseEvent provides a mock function with given fields: _a0, _a1
func (_m *MockAnalyticWriterService) CreateDSPToExchangeResponseEvent(_a0 context.Context, _a1 model.CreateDSPToExchangeResponseEventReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateDSPToExchangeResponseEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateDSPToExchangeResponseEventReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateExchangeToDSPRequestEvent provides a mock function with given fields: _a0, _a1
func (_m *MockAnalyticWriterService) CreateExchangeToDSPRequestEvent(_a0 context.Context, _a1 model.CreateExchangeToDSPRequestEventReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateExchangeToDSPRequestEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateExchangeToDSPRequestEventReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateExchangeToSSPResponseEvent provides a mock function with given fields: _a0, _a1
func (_m *MockAnalyticWriterService) CreateExchangeToSSPResponseEvent(_a0 context.Context, _a1 model.CreateExchangeToSSPResponseEventReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateExchangeToSSPResponseEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateExchangeToSSPResponseEventReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSSPToExchangeRequestEvent provides a mock function with given fields: _a0, _a1
func (_m *MockAnalyticWriterService) CreateSSPToExchangeRequestEvent(_a0 context.Context, _a1 model.CreateSSPToExchangeRequestEventReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateSSPToExchangeRequestEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateSSPToExchangeRequestEventReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAnalyticWriterService creates a new instance of MockAnalyticWriterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticWriterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticWriterService {
	mock := &MockAnalyticWriterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
