// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	model "exchange/internal/services/user/model"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

// FindUsers provides a mock function with given fields: _a0, _a1
func (_m *MockUserService) FindUsers(_a0 context.Context, _a1 model.FindUsersReq) (model.FindUsersRes, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindUsers")
	}

	var r0 model.FindUsersRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.FindUsersReq) (model.FindUsersRes, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.FindUsersReq) model.FindUsersRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.FindUsersRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.FindUsersReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastLoginAt provides a mock function with given fields: _a0, _a1
func (_m *MockUserService) UpdateLastLoginAt(_a0 context.Context, _a1 model.UpdateLastLoginAtReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLoginAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UpdateLastLoginAtReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
