// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockEbayNetwork is an autogenerated mock type for the EbayNetwork type
type MockEbayNetwork struct {
	mock.Mock
}

// NewMockEbayNetwork creates a new instance of MockEbayNetwork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEbayNetwork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEbayNetwork {
	mock := &MockEbayNetwork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
