// Code generated by mockery v2.46.2. DO NOT EDIT.

package beforeAuction

import (
	context "context"
	model "exchange/internal/services/exchange/model"

	mock "github.com/stretchr/testify/mock"
)

// MockExchangeRepository is an autogenerated mock type for the ExchangeRepository type
type MockExchangeRepository struct {
	mock.Mock
}

// GetPublisherVisibility provides a mock function with given fields: ctx, publisherID
func (_m *MockExchangeRepository) GetPublisherVisibility(ctx context.Context, publisherID string) (model.PublisherVisibility, error) {
	ret := _m.Called(ctx, publisherID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublisherVisibility")
	}

	var r0 model.PublisherVisibility
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PublisherVisibility, error)); ok {
		return rf(ctx, publisherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PublisherVisibility); ok {
		r0 = rf(ctx, publisherID)
	} else {
		r0 = ret.Get(0).(model.PublisherVisibility)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publisherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockExchangeRepository creates a new instance of MockExchangeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExchangeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExchangeRepository {
	mock := &MockExchangeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
