// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	model "generator/internal/services/horoscope/model"

	mock "github.com/stretchr/testify/mock"
)

// MockHoroscopeRepository is an autogenerated mock type for the HoroscopeRepository type
type MockHoroscopeRepository struct {
	mock.Mock
}

// CreateHoroscope provides a mock function with given fields: _a0, _a1
func (_m *MockHoroscopeRepository) CreateHoroscope(_a0 context.Context, _a1 model.CreateHoroscopeReq) (uint32, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateHoroscope")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateHoroscopeReq) (uint32, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateHoroscopeReq) uint32); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateHoroscopeReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHoroscopes provides a mock function with given fields: _a0, _a1
func (_m *MockHoroscopeRepository) GetHoroscopes(_a0 context.Context, _a1 model.GetHoroscopesReq) ([]model.Horoscope, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetHoroscopes")
	}

	var r0 []model.Horoscope
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetHoroscopesReq) ([]model.Horoscope, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetHoroscopesReq) []model.Horoscope); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Horoscope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetHoroscopesReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockHoroscopeRepository creates a new instance of MockHoroscopeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHoroscopeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHoroscopeRepository {
	mock := &MockHoroscopeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
