// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	model "generator/internal/services/forecast/model"

	mock "github.com/stretchr/testify/mock"
)

// MockForecastRepository is an autogenerated mock type for the ForecastRepository type
type MockForecastRepository struct {
	mock.Mock
}

// CreateForecast provides a mock function with given fields: _a0, _a1
func (_m *MockForecastRepository) CreateForecast(_a0 context.Context, _a1 model.CreateForecastReq) (uint32, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateForecast")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateForecastReq) (uint32, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateForecastReq) uint32); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateForecastReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForecasts provides a mock function with given fields: _a0, _a1
func (_m *MockForecastRepository) GetForecasts(_a0 context.Context, _a1 model.GetForecastsReq) ([]model.Forecast, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetForecasts")
	}

	var r0 []model.Forecast
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetForecastsReq) ([]model.Forecast, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetForecastsReq) []model.Forecast); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Forecast)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetForecastsReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockForecastRepository creates a new instance of MockForecastRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForecastRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForecastRepository {
	mock := &MockForecastRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
