// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	model "exchange/internal/services/analyticWriter/model"

	mock "github.com/stretchr/testify/mock"
)

// MockAnalyticWriterService is an autogenerated mock type for the AnalyticWriterService type
type MockAnalyticWriterService struct {
	mock.Mock
}

// CreateDSPBillingEventReq provides a mock function with given fields: _a0, _a1
func (_m *MockAnalyticWriterService) CreateDSPBillingEventReq(_a0 context.Context, _a1 model.CreateDSPBillingEventReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateDSPBillingEventReq")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateDSPBillingEventReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSSPBillingEventReq provides a mock function with given fields: _a0, _a1
func (_m *MockAnalyticWriterService) CreateSSPBillingEventReq(_a0 context.Context, _a1 model.CreateSSPBillingEventReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateSSPBillingEventReq")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateSSPBillingEventReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAnalyticWriterService creates a new instance of MockAnalyticWriterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticWriterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticWriterService {
	mock := &MockAnalyticWriterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
