// Code generated by mockery v2.46.2. DO NOT EDIT.

package endpoint

import mock "github.com/stretchr/testify/mock"

// MockEbayService is an autogenerated mock type for the EbayService type
type MockEbayService struct {
	mock.Mock
}

// NewMockEbayService creates a new instance of MockEbayService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEbayService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEbayService {
	mock := &MockEbayService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
