// Code generated by mockery v2.46.2. DO NOT EDIT.

package scheduler

import (
	context "context"
	model "server/internal/services/generator/model"

	mock "github.com/stretchr/testify/mock"
)

// MockGeneratorService is an autogenerated mock type for the GeneratorService type
type MockGeneratorService struct {
	mock.Mock
}

// GenerateDailyZodiacForecast provides a mock function with given fields: ctx, req
func (_m *MockGeneratorService) GenerateDailyZodiacForecast(ctx context.Context, req model.GenerateDailyZodiacForecastReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDailyZodiacForecast")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GenerateDailyZodiacForecastReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockGeneratorService creates a new instance of MockGeneratorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeneratorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeneratorService {
	mock := &MockGeneratorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
