// Code generated by mockery v2.46.2. DO NOT EDIT.

package beforeAnalytic

import mock "github.com/stretchr/testify/mock"

// MockExchangeRepository is an autogenerated mock type for the ExchangeRepository type
type MockExchangeRepository struct {
	mock.Mock
}

// GetCountryByIP provides a mock function with given fields: ipStr
func (_m *MockExchangeRepository) GetCountryByIP(ipStr string) (string, error) {
	ret := _m.Called(ipStr)

	if len(ret) == 0 {
		panic("no return value specified for GetCountryByIP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(ipStr)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(ipStr)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ipStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockExchangeRepository creates a new instance of MockExchangeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExchangeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExchangeRepository {
	mock := &MockExchangeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
