// Code generated by mockery v2.46.2. DO NOT EDIT.

package authManager

import (
	context "context"
	model "partners/internal/services/ebay/network/model"

	mock "github.com/stretchr/testify/mock"
)

// MockEbayNetwork is an autogenerated mock type for the EbayNetwork type
type MockEbayNetwork struct {
	mock.Mock
}

// Auth provides a mock function with given fields: _a0, _a1
func (_m *MockEbayNetwork) Auth(_a0 context.Context, _a1 model.AuthReq) (model.AuthRes, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 model.AuthRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthReq) (model.AuthRes, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthReq) model.AuthRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.AuthRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AuthReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEbayNetwork creates a new instance of MockEbayNetwork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEbayNetwork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEbayNetwork {
	mock := &MockEbayNetwork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
