// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	openrtb "pkg/openrtb"

	mock "github.com/stretchr/testify/mock"
)

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

// CreateExchangeBidRequestToDSPEvent provides a mock function with given fields: _a0, _a1
func (_m *MockEventRepository) CreateExchangeBidRequestToDSPEvent(_a0 context.Context, _a1 openrtb.BidRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateExchangeBidRequestToDSPEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, openrtb.BidRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateExchangeBidResponseToSSPEvent provides a mock function with given fields: _a0, _a1
func (_m *MockEventRepository) CreateExchangeBidResponseToSSPEvent(_a0 context.Context, _a1 openrtb.BidResponse) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateExchangeBidResponseToSSPEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, openrtb.BidResponse) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSSPBidRequestToExchangeEvent provides a mock function with given fields: _a0, _a1
func (_m *MockEventRepository) CreateSSPBidRequestToExchangeEvent(_a0 context.Context, _a1 openrtb.BidRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateSSPBidRequestToExchangeEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, openrtb.BidRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrementLoadsForPublisher provides a mock function with given fields: _a0, _a1
func (_m *MockEventRepository) IncrementLoadsForPublisher(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IncrementLoadsForPublisher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrementViewsForPublisher provides a mock function with given fields: _a0, _a1
func (_m *MockEventRepository) IncrementViewsForPublisher(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViewsForPublisher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
