name: go-test

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download submodules
        run: git submodule update --init --recursive

        # Настраиваем Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: go.sum

        # Устанавливаем mockery
      - name: Install mockery
        run: go install github.com/vektra/mockery/v2@latest

        # Генерируем моки
      - name: Generate mocks
        run: mockery

        # Генерируем swagger
      - name: Generate swagger
        run: |
          cd ${{ inputs.service_name }}
          go generate ./...

        # Тестируем код
      - name: Go test
        run: |
          cd ${{ inputs.service_name }}
          go test -v ./...
