name: prod deploy

on:
  push:
    tags:
      - v*
    paths:
      - 'partners/**'

jobs:
  general-deploy-pipeline:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_port: 8082
      service_name: partners
      command_args: -log-format=text -env-mode=prod
    secrets: inherit
